#+SETUPFILE: ~/.emacs.d/setup-file-html.org
#+OPTIONS: H:4 toc:nil ^:nil num:nil

* Analyse Code Source

Le code source se trouve dans les dossiers:
- /App/
- /pdb/
- /plug-ins/
- /libgimp/
- /libgimpbase/
- /libgimpcolor/
- /libgimpconfig/
- /libgimpmath/
- /libgimpmodule/
- /libgimpthumb/
- /tools/

#+CAPTION: Arborescence du dossier /App/
#+BEGIN_SRC text
  app 
  ├── actions	Gestion d'évènements de l'application
  ├── config	Configurations de l'environnement de GIMP
  ├── core	
  ├── dialogs
  ├── display
  ├── file
  ├── gegl
  ├── gui
  ├── menus
  ├── operations
  │   ├── layer-modes
  │   ├── layer-modes-legacy
  │   └── tests
  │       └── data
  ├── paint
  ├── pdb
  ├── plug-in
  ├── propgui
  ├── tests
  │   ├── files
  │   ├── gimpdir
  │   │   ├── brushes
  │   │   ├── gradients
  │   │   └── patterns
  │   └── gimpdir-empty
  │       ├── brushes
  │       ├── gradients
  │       └── patterns
  ├── text
  ├── tools
  ├── vectors
  ├── widgets
  └── xcf

#+END_SRC

** Justifications
*** app
**** actions

On y trouve beaucoup noms de fichiers de la forme <element>-actions ou <element>-commands. Cela peut correspondre aux actions liés aux évènements des éléments de l'application. (Une action = ce qui s'execute après qu'on interagit avec un élément).
**** config

On y trouve des fichiers qui définissent des types, structures, constantes tels que /config-enums.c/, /config-types.c/.
Ce qui faut nous dit que c'est la configuration de l'environnement de développement de GIMP.
**** core

La traduction core est choeur ce qui nous fait penser au fonctionalités plus importantes du GIMP. En regardant les fichiers on voit des noms comme /gimpasync.c/, /core-enums.c/, /gimpmybrush-load.c/; /gimppalette.c/, /gimpparamspecs.c/, /gimppattern-load.c/ faisant référence à des fonctionnalités générales.
**** dialogs

D'après les noms des fichiers /quit-dialog.c/, /resize-diaog.c/, scale-dialog.c/, stroke-dialog.c/, /about-dialog.c/, /dialogs.c/ ainsi que le nom du dossier on peut dire que ce dossier contient le code gérant les boîtes de dialogue.
**** display

On s'attend d'après le nom du dossier à du code gérant les fênetres et l'affichage. On le confirme grâce aux noms des fichiers /gimpcanvasarc.c/, /gimpcanvas.c/, /gimpcanvasrectangle.c/, /gimpstatusbar.c/, etc.
**** file

Les fichiers /file-import.c/, /file-open.c/, /file-save.c/, /gimp-file.c/ nous disent que ce dossier contient le code gérant la manipulation de fichiers.
**** gegl

"General Graphics Library" est une bibliothèque logiciel graphique  en cours de développement utilisé dans GIMP de façon expérimentale (https://docs.gimp.org/2.10/en/gimp-tool-gegl.html). Ce dossier contient donc le code qui utilise la bibliothèque.
**** gui

D'après le nom gui (Graphical User Interface) on s'attend à du code gérant l'interface graphique. On le confirme en fouillant les fichiers tels que /themes.c/, /session.c/, /gui.c/, /icon-themes.c/, /splash.c/.
**** menus

Avec le même raisonnement que dans le dossier /gui/ on voit qu'il s'agit du code gérant les menus de GIMP.
**** operations

D'après les noms de fichiers /gimpbrightnessconstratconfig.c/, /gimpoperationcolorize.c/, /gimpoperationcurves.c/, /gimpoperationgradient.c/, /gimpoperationthresholdalpha.c/, on remarque que il s'agit du code définissant les opérations sur les couches d'images (/layers/).
**** paint

Code gérant les outils de dessin (/gimpairbrush.c/, /gimperaser.c/, /gimpbrushcore.c/, /gimppencil.c/, /gimpsmudge.c/, etc)
**** pdb

D'après le fichier README ce dossier contient les fonctions "wrappers" du PDB servant à plusieurs fonctions internes de GIMP.
**** plug-in

Code gérant les plug-ins de GIMP.
**** propgui

Code gérant des effets et transformations des images. Vu la présence
des fichiers avec le motif gimppropgui-<nom de l'efft>.c.

**** tests

Ce dossier contient le code permettant de tester plusieurs fonctionnalités de GIMP.
**** text

Code gérant le texte sur des couches d'images (/gimptextlayer-xcf.c/, /gimptext-xlfd.c/, /gimptext.c/, /gimptextundo.c/).
- XCF = Extension utilisé par GIMP pour garder des format d'image
- XLFD = X logical font description (norme des polices)
**** tools

Code définissant les outils de manipulation d'image de GIMP (/gimprotatetool.c/, /gimpsmudgetool.c/, /gimptexttool.c/ (On remarque le motif gimp<outil>tool.c))
**** vectors

Code définissant les vecteurs d'image servant aux traçage de droites, projections (/gimpstroke.c/, /gimpvectors.c/, /gimpanchor.c/)
**** widgets

Code définissant les éléments graphiques avec lesquels on peut intéragir tels que (/gimpcolorbar.c/, /gimpcellrendererbutton.c/, /gimppickablebutton.c/, etc, ...).
**** xcf

Code gérant la manipulation des fichiers xcf (format de GIMP). Actions vues dans les fichiers:
- load
- read
- save
- seek
- write
- ...
     
